In [1]:
import pandas as pd
import numpy as np
path= r"C:\Users\DELL\Desktop\ml\Cellphone.xlsx"
df=pd.read_excel(path)
print(df.head())

   Product_id  Price  Sale  weight  resoloution  ppi  cpu core  cpu freq  \
0         203   2357    10   135.0          5.2  424         8      1.35
1         880   1749    10   125.0          4.0  233         2      1.30
2          40   1916    10   110.0          4.7  312         4      1.20
3          99   1315    11   118.5          4.0  233         2      1.30
4         880   1749    11   125.0          4.0  233         2      1.30

   internal mem    ram  RearCam  Front_Cam  battery  thickness
0          16.0  3.000    13.00        8.0     2610        7.4
1           4.0  1.000     3.15        0.0     1700        9.9
2           8.0  1.500    13.00        5.0     2000        7.6
3           4.0  0.512     3.15        0.0     1400       11.0
4           4.0  1.000     3.15        0.0     1700        9.9

In [2]:
df.isnull().sum()

Product_id      0
Price           0
Sale            0
weight          0
resoloution     0
ppi             0
cpu core        0
cpu freq        0
internal mem    0
ram             0
RearCam         0
Front_Cam       0
battery         0
thickness       0
dtype: int64

In [3]:
df.columns=df.columns.str.lower()
df.columns

Index(['product_id', 'price', 'sale', 'weight', 'resoloution', 'ppi',
       'cpu core', 'cpu freq', 'internal mem', 'ram', 'rearcam', 'front_cam',
       'battery', 'thickness'],
      dtype='object')

In [5]:
df.columns=df.columns.str.replace(' ','_')
df.columns

Index(['product_id', 'price', 'sale', 'weight', 'resoloution', 'ppi',
       'cpu_core', 'cpu_freq', 'internal_mem', 'ram', 'rearcam', 'front_cam',
       'battery', 'thickness'],
      dtype='object')

In [6]:
df.head()

,product_id,price,sale,weight,resoloution,ppi,cpu_core,cpu_freq,internal_mem,ram,rearcam,front_cam,battery,thickness
0,203,2357,10,135.0,5.2,424,8,1.35,16.0,3.000,13.00,8.0,2610,7.4
1,880,1749,10,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9
2,40,1916,10,110.0,4.7,312,4,1.20,8.0,1.500,13.00,5.0,2000,7.6
3,99,1315,11,118.5,4.0,233,2,1.30,4.0,0.512,3.15,0.0,1400,11.0
4,880,1749,11,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9

In [7]:
df.duplicated()  # Returns a boolean series indicating duplicate rows

0      False
1      False
2      False
3      False
4      False
       ...
156    False
157    False
158    False
159    False
160    False
Length: 161, dtype: bool

In [10]:
df.columns = df.columns.str.strip()
df.columns

Index(['product_id', 'price', 'sale', 'weight', 'resoloution', 'ppi',
       'cpu_core', 'cpu_freq', 'internal_mem', 'ram', 'rearcam', 'front_cam',
       'battery', 'thickness'],
      dtype='object')

In [11]:
df['price_per_ram'] = df['price'] / df['ram']
df.head()

,product_id,price,sale,weight,resoloution,ppi,cpu_core,cpu_freq,internal_mem,ram,rearcam,front_cam,battery,thickness,price_per_ram
0,203,2357,10,135.0,5.2,424,8,1.35,16.0,3.000,13.00,8.0,2610,7.4,785.666667
1,880,1749,10,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9,1749.000000
2,40,1916,10,110.0,4.7,312,4,1.20,8.0,1.500,13.00,5.0,2000,7.6,1277.333333
3,99,1315,11,118.5,4.0,233,2,1.30,4.0,0.512,3.15,0.0,1400,11.0,2568.359375
4,880,1749,11,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9,1749.000000

In [12]:
df['cpu_power'] = df['cpu_core'] * df['cpu_freq']
df.head()

,product_id,price,sale,weight,resoloution,ppi,cpu_core,cpu_freq,internal_mem,ram,rearcam,front_cam,battery,thickness,price_per_ram,cpu_power
0,203,2357,10,135.0,5.2,424,8,1.35,16.0,3.000,13.00,8.0,2610,7.4,785.666667,10.8
1,880,1749,10,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9,1749.000000,2.6
2,40,1916,10,110.0,4.7,312,4,1.20,8.0,1.500,13.00,5.0,2000,7.6,1277.333333,4.8
3,99,1315,11,118.5,4.0,233,2,1.30,4.0,0.512,3.15,0.0,1400,11.0,2568.359375,2.6
4,880,1749,11,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9,1749.000000,2.6

In [16]:
bins = [0, 10000, 30000, 50000, float('inf')]
labels = ['budget', 'mid_range', 'premium', 'high_end']
df['price_category'] = pd.cut(df['price'], bins=bins, labels=labels)
df.iloc[30:50]

,product_id,price,sale,weight,resoloution,ppi,cpu_core,cpu_freq,internal_mem,ram,rearcam,front_cam,battery,thickness,price_per_ram,cpu_power,price_category
30,187,2258,26,150.0,5.0,441,4,2.300,16.0,2.000,13.0,2.0,2300,10.0,1129.000000,9.20,budget
31,990,2977,26,152.0,5.1,577,8,2.300,32.0,4.000,12.0,5.0,3000,7.9,744.250000,18.40,budget
32,1145,3316,26,144.0,5.2,428,8,1.750,32.0,3.000,20.7,5.1,2930,6.9,1105.333333,14.00,budget
33,1020,2654,30,151.0,5.7,386,8,1.550,32.0,2.000,16.0,5.0,3050,5.9,1327.000000,12.40,budget
34,1339,1421,31,120.0,4.0,233,2,1.000,4.0,0.512,2.0,0.0,1200,9.8,2775.390625,2.00,budget
35,1020,2654,32,151.0,5.7,386,8,1.550,32.0,2.000,16.0,5.0,3050,5.9,1327.000000,12.40,budget
36,104,1942,34,139.2,4.7,469,4,2.150,16.0,2.000,16.0,4.0,2200,10.3,971.000000,8.60,budget
37,662,2124,35,489.0,10.1,224,4,2.260,16.0,2.000,5.0,2.0,7400,7.8,1062.000000,9.04,budget
38,575,1777,36,174.0,5.5,178,4,1.300,4.0,0.512,5.0,0.0,2250,9.2,3470.703125,5.20,budget
39,860,2392,36,147.0,5.2,282,8,1.400,32.0,3.000,13.0,16.0,2900,7.7,797.333333,11.20,budget
40,662,2124,37,489.0,10.1,224,4,2.260,16.0,2.000,5.0,2.0,7400,7.8,1062.000000,9.04,budget
41,907,2087,37,147.0,5.0,294,4,1.300,32.0,3.000,8.0,5.0,2450,7.6,695.666667,5.20,budget
42,162,1843,38,133.5,4.5,218,4,1.300,8.0,1.000,5.0,0.0,1600,10.1,1843.000000,5.20,budget
43,907,2087,40,147.0,5.0,294,4,1.300,32.0,3.000,8.0,5.0,2450,7.6,695.666667,5.20,budget
44,974,2859,40,169.0,5.7,515,4,1.875,64.0,4.000,12.0,5.0,3500,7.9,714.750000,7.50,budget
45,739,1989,40,131.0,5.0,294,4,1.300,16.0,2.000,13.0,5.0,2500,8.7,994.500000,5.20,budget
46,1339,1421,40,120.0,4.0,233,2,1.000,4.0,0.512,2.0,0.0,1200,9.8,2775.390625,2.00,budget
47,1145,3316,41,144.0,5.2,428,8,1.750,32.0,3.000,20.7,5.1,2930,6.9,1105.333333,14.00,budget
48,162,1843,41,133.5,4.5,218,4,1.300,8.0,1.000,5.0,0.0,1600,10.1,1843.000000,5.20,budget
49,738,2685,42,168.0,5.7,386,8,1.800,32.0,3.000,21.0,5.0,3050,7.5,895.000000,14.40,budget

In [20]:
#df=df.drop(columns=['price_category'],inplace=True)
df.head()

,product_id,price,sale,weight,resoloution,ppi,cpu_core,cpu_freq,internal_mem,ram,rearcam,front_cam,battery,thickness,price_per_ram,cpu_power
0,203,2357,10,135.0,5.2,424,8,1.35,16.0,3.000,13.00,8.0,2610,7.4,785.666667,10.8
1,880,1749,10,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9,1749.000000,2.6
2,40,1916,10,110.0,4.7,312,4,1.20,8.0,1.500,13.00,5.0,2000,7.6,1277.333333,4.8
3,99,1315,11,118.5,4.0,233,2,1.30,4.0,0.512,3.15,0.0,1400,11.0,2568.359375,2.6
4,880,1749,11,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9,1749.000000,2.6

In [22]:
df.to_excel(r'C:\Users\DELL\Desktop\ml.xlsx', index=False)